# COVID-19 - Clinical Data to assess diagnosis

## Sírio-Libanês data for AI and Analytics 

https://www.kaggle.com/S%C3%ADrio-Libanes/covid19

Task: Predict admission to the ICU of confirmed COVID-19 cases.

In [ ]:
pip install pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Kaggle_Sirio_Libanes_ICU_Prediction.csv')

In [4]:
df.head()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU
0,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0-2,0
1,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,0
2,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4-6,0
3,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,NaN,NaN,NaN,NaN,-1.000000,-1.000000,6-12,0
4,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.238095,-0.818182,-0.389967,0.407558,-0.230462,0.096774,-0.242282,-0.814433,ABOVE_12,1

In [5]:
df.shape

(1925, 231)

In [6]:
df.describe()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,HTN,...,RESPIRATORY_RATE_DIFF,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,ICU
count,1925.000000,1925.000000,1925.000000,1920.000000,1920.000000,1920.000000,1920.000000,1920.000000,1920.000000,1920.000000,...,1177.000000,1231.000000,1239.000000,1240.000000,1240.000000,1240.000000,1177.000000,1231.000000,1239.000000,1925.000000
mean,192.000000,0.467532,0.368831,0.108333,0.028125,0.097917,0.019792,0.128125,0.046875,0.213021,...,-0.703683,-0.770338,-0.887196,-0.786997,-0.715950,-0.817800,-0.719147,-0.771327,-0.886982,0.267532
std,111.168431,0.499074,0.482613,0.310882,0.165373,0.297279,0.139320,0.334316,0.211426,0.409549,...,0.482097,0.319001,0.296147,0.324754,0.419103,0.270217,0.446600,0.317694,0.296772,0.442787
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,96.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
50%,192.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,-0.976190,-0.979798,-1.000000,-0.984944,-0.989822,-1.000000,-0.975924,-0.980333,0.000000
75%,288.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.647059,-0.595238,-0.878788,-0.645482,-0.522176,-0.662529,-0.634409,-0.594677,-0.880155,1.000000
max,384.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Numerical and Categorical Features

In [7]:
#Numerical Features
cols = df.columns
num_cols = df._get_numeric_data().columns
num_cols

Index(['PATIENT_VISIT_IDENTIFIER', 'AGE_ABOVE65', 'GENDER',
       'DISEASE GROUPING 1', 'DISEASE GROUPING 2', 'DISEASE GROUPING 3',
       'DISEASE GROUPING 4', 'DISEASE GROUPING 5', 'DISEASE GROUPING 6', 'HTN',
       ...
       'RESPIRATORY_RATE_DIFF', 'TEMPERATURE_DIFF', 'OXYGEN_SATURATION_DIFF',
       'BLOODPRESSURE_DIASTOLIC_DIFF_REL', 'BLOODPRESSURE_SISTOLIC_DIFF_REL',
       'HEART_RATE_DIFF_REL', 'RESPIRATORY_RATE_DIFF_REL',
       'TEMPERATURE_DIFF_REL', 'OXYGEN_SATURATION_DIFF_REL', 'ICU'],
      dtype='object', length=229)

In [8]:
#Categorical Features
cat_cols = list(set(cols) - set(num_cols))
cat_cols

['WINDOW', 'AGE_PERCENTIL']

### Categorical Features : AGE_PERCENTIL, WINDOW

In [9]:
print(df['AGE_PERCENTIL'].unique())
print(df['WINDOW'].unique())

['60th' '90th' '10th' '40th' '70th' '20th' '50th' '80th' '30th'
 'Above 90th']
['0-2' '2-4' '4-6' '6-12' 'ABOVE_12']

In [10]:
ptile = []
for j in df['AGE_PERCENTIL']:
    if j == 'Above 90th':
        ptile.append(temp)
    
    else:
        temp = int(j.replace('th',""))
        ptile.append(temp)

In [11]:
df['AGE_PERCENTIL'] = ptile

In [12]:
df['AGE_PERCENTIL']

0       60
1       60
2       60
3       60
4       60
        ..
1920    50
1921    50
1922    50
1923    50
1924    50
Name: AGE_PERCENTIL, Length: 1925, dtype: int64

In [13]:
window = []
for k in df['WINDOW']:
    if(k == '0-2'):
        window.append(1)
    
    if(k == '2-4'):
        window.append(3)
        
    if(k == '4-6'):
        window.append(5)
        
    if(k == '6-12'):
        window.append(9)
    
    if(k == 'ABOVE_12'):
        window.append(15)
    
df['WINDOW'] = window

In [14]:
df['WINDOW']

0        1
1        3
2        5
3        9
4       15
        ..
1920     1
1921     3
1922     5
1923     9
1924    15
Name: WINDOW, Length: 1925, dtype: int64

## NULL/Missing Values Handling

In [15]:
#Null Values
df.isnull().sum()

PATIENT_VISIT_IDENTIFIER        0
AGE_ABOVE65                     0
AGE_PERCENTIL                   0
GENDER                          0
DISEASE GROUPING 1              5
                             ...
RESPIRATORY_RATE_DIFF_REL     748
TEMPERATURE_DIFF_REL          694
OXYGEN_SATURATION_DIFF_REL    686
WINDOW                          0
ICU                             0
Length: 231, dtype: int64

In [16]:
#Filling with Median
for i in cols:
    df[i].fillna(df[i].median(), inplace=True)

In [17]:
df.head()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU
0,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1,0
1,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3,0
2,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.976190,-0.979798,-1.000000,-0.984944,-0.989822,-1.000000,-0.975924,-0.980333,5,0
3,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-0.984944,-0.989822,-1.000000,-1.000000,-1.000000,9,0
4,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.238095,-0.818182,-0.389967,0.407558,-0.230462,0.096774,-0.242282,-0.814433,15,1

In [18]:
df.isnull().sum()

PATIENT_VISIT_IDENTIFIER      0
AGE_ABOVE65                   0
AGE_PERCENTIL                 0
GENDER                        0
DISEASE GROUPING 1            0
                             ..
RESPIRATORY_RATE_DIFF_REL     0
TEMPERATURE_DIFF_REL          0
OXYGEN_SATURATION_DIFF_REL    0
WINDOW                        0
ICU                           0
Length: 231, dtype: int64

## Data Visualization

In [19]:
pip install seaborn

Requirement already satisfied: seaborn in d:\anaconda\envs\covidhpred\lib\site-packages (0.11.1)
Requirement already satisfied: scipy>=1.0 in d:\anaconda\envs\covidhpred\lib\site-packages (from seaborn) (1.7.0)
Requirement already satisfied: matplotlib>=2.2 in d:\anaconda\envs\covidhpred\lib\site-packages (from seaborn) (3.4.2)
Requirement already satisfied: numpy>=1.15 in d:\anaconda\envs\covidhpred\lib\site-packages (from seaborn) (1.21.1)
Requirement already satisfied: pandas>=0.23 in d:\anaconda\envs\covidhpred\lib\site-packages (from seaborn) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda\envs\covidhpred\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: cycler>=0.10 in d:\anaconda\envs\covidhpred\lib\site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\anaconda\envs\covidhpred\lib\site-packages (from matplotlib>=2.2->seaborn) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in d:\anaconda\envs\covidhpred\lib\site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in d:\anaconda\envs\covidhpred\lib\site-packages (from matplotlib>=2.2->seaborn) (8.3.1)
Requirement already satisfied: six in d:\anaconda\envs\covidhpred\lib\site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in d:\anaconda\envs\covidhpred\lib\site-packages (from pandas>=0.23->seaborn) (2021.1)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import seaborn as sns

In [21]:
df.corr()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU
PATIENT_VISIT_IDENTIFIER,1.000000e+00,-3.072713e-02,-9.463622e-03,5.977220e-02,0.076320,0.044839,0.040954,-0.017036,0.009198,0.014369,...,-0.012977,-0.044082,-0.008689,-0.017208,-0.028716,-0.011562,-0.012756,-0.044063,1.535110e-16,-0.047547
AGE_ABOVE65,-3.072713e-02,1.000000e+00,7.820200e-01,4.974367e-02,0.267472,0.067804,0.158191,0.016719,0.305579,-0.015180,...,0.052760,0.086149,0.094569,0.108719,0.041164,0.090640,0.053683,0.087170,3.269443e-17,0.212198
AGE_PERCENTIL,-9.463622e-03,7.820200e-01,1.000000e+00,2.792880e-02,0.233388,0.106333,0.150409,0.027495,0.276346,-0.028560,...,0.057899,0.058922,0.074703,0.089324,0.034272,0.069902,0.058505,0.059803,3.359970e-17,0.169763
GENDER,5.977220e-02,4.974367e-02,2.792880e-02,1.000000e+00,0.039131,-0.032060,-0.073772,-0.054300,-0.021712,-0.016294,...,-0.040538,-0.031321,0.004167,0.000325,-0.033260,-0.022543,-0.040057,-0.031323,7.513238e-18,-0.065543
DISEASE GROUPING 1,7.631973e-02,2.674725e-01,2.333879e-01,3.913143e-02,1.000000,0.194220,0.240615,0.010754,0.332901,0.168636,...,0.045308,0.007743,0.081514,0.079791,0.069279,0.065424,0.046133,0.007673,4.625055e-02,0.061817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RESPIRATORY_RATE_DIFF_REL,-1.156218e-02,9.064011e-02,6.990208e-02,-2.254280e-02,0.065424,0.095730,0.109043,0.041736,0.086931,0.063714,...,0.842557,0.599111,0.848443,0.870182,0.836605,1.000000,0.843181,0.598896,6.919253e-01,0.507017
TEMPERATURE_DIFF_REL,-1.275611e-02,5.368349e-02,5.850469e-02,-4.005703e-02,0.046133,0.085033,0.098116,0.024037,0.055871,0.078373,...,0.999911,0.569445,0.851728,0.881052,0.866529,0.843181,1.000000,0.569578,7.675194e-01,0.377222
OXYGEN_SATURATION_DIFF_REL,-4.406337e-02,8.717034e-02,5.980314e-02,-3.132319e-02,0.007673,0.093249,0.085512,0.030519,0.040175,0.051886,...,0.569789,0.999836,0.597340,0.613764,0.572701,0.598896,0.569578,1.000000,4.278609e-01,0.277248
WINDOW,1.535110e-16,3.269443e-17,3.359970e-17,7.513238e-18,0.046251,0.047915,0.063174,0.011435,0.032726,0.062461,...,0.767210,0.428003,0.706682,0.725331,0.746607,0.691925,0.767519,0.427861,1.000000e+00,0.330974
ICU,-4.754667e-02,2.121978e-01,1.697630e-01,-6.554320e-02,0.061817,0.082108,0.077892,0.057650,0.088532,-0.005992,...,0.376758,0.276167,0.423547,0.444490,0.379325,0.507017,0.377222,0.277248,3.309745e-01,1.000000

In [22]:
#independent and dependent features
X=df.iloc[:,:-1] 
y=df.iloc[:,-1]

In [23]:
X

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,RESPIRATORY_RATE_DIFF,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW
0,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1
1,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3
2,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-0.976190,-0.979798,-1.000000,-0.984944,-0.989822,-1.000000,-0.975924,-0.980333,5
3,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-0.984944,-0.989822,-1.000000,-1.000000,-1.000000,9
4,0,1,60,0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.176471,-0.238095,-0.818182,-0.389967,0.407558,-0.230462,0.096774,-0.242282,-0.814433,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920,384,0,50,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1
1921,384,0,50,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3
1922,384,0,50,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,5
1923,384,0,50,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,9
1924,384,0,50,1,0.0,0.0,1.0,0.0,0.0,0.0,...,-0.647059,-0.547619,-0.838384,-0.701863,-0.585967,-0.763868,-0.612903,-0.551337,-0.835052,15

In [24]:
y

0       0
1       0
2       0
3       0
4       1
       ..
1920    0
1921    0
1922    0
1923    0
1924    0
Name: ICU, Length: 1925, dtype: int64

## Train-Test Split

In [25]:
pip install sklearn

Requirement already satisfied: sklearn in d:\anaconda\envs\covidhpred\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in d:\anaconda\envs\covidhpred\lib\site-packages (from sklearn) (0.24.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda\envs\covidhpred\lib\site-packages (from scikit-learn->sklearn) (2.2.0)
Requirement already satisfied: numpy>=1.13.3 in d:\anaconda\envs\covidhpred\lib\site-packages (from scikit-learn->sklearn) (1.21.1)
Requirement already satisfied: scipy>=0.19.1 in d:\anaconda\envs\covidhpred\lib\site-packages (from scikit-learn->sklearn) (1.7.0)
Requirement already satisfied: joblib>=0.11 in d:\anaconda\envs\covidhpred\lib\site-packages (from scikit-learn->sklearn) (1.0.1)
Note: you may need to restart the kernel to use updated packages.

## Gaussian NaiveBayes

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"
      % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 963 points : 217

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.77466251298027

## Regression Trees Classifier

In [27]:
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
model = ExtraTreesClassifier()
model.fit(X_train,y_train)

ExtraTreesClassifier()

In [28]:
y_predicted = model.predict(X_test)

In [56]:
accuracy_score(y_test, y_predicted)

0.8629283489096573

In [41]:
import pickle
file = open('rfclassifier_model.pkl', 'wb')

pickle.dump(model, file)